sudo: false
language: python
require: selenium-webdriver

matrix:
    include:
      - python: 3.6
        env: TOXENV=py36
      - python: 3.7
        env: TOXENV=py37
      - python: 3.8
        env: TOXENV=py38

script: tox

install:
    - pip install tox
    - pip install poetry
    - pip install codecov

after_script:
    - codecov
